apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: naseemahmad244/auth
        envFrom:
        - secretRef:
            name: auth-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-serv
spec:
  selector:
    app: auth
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP

